matrix:
  include:
    - os: linux
      sudo: required
    - os: osx

language: node_js
node_js: "8"

before_install:
  - ./install_deps.sh
  - . get_repo.sh
  - . check_tags.sh

script:
  - ./build.sh

before_deploy:
  - ./create_zip.sh

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: ./*.zip
  on:
    condition: "$SHOULD_BUILD = yes"
